server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5430/demoDB
    username: postgres
    password: sigma05
  flyway:
    url: jdbc:postgresql://localhost:5430/demoDB
    user: postgres
    password: sigma05


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE